# Create table
## Create customer table
CREATE TABLE customer_master(ID VARCHAR(10), Customer_name VARCHAR(30), Transactions INT, Last_Transaction DATE);

## Create transaction table
CREATE TABLE transactions(Transaction_ID VARCHAR(10), Customer_ID VARCHAR(10), Quantity INT, Amount INT);

## Create Shipping charges table
CREATE TABLE delivery_charges(Location_ID VARCHAR(10), Location VARCHAR(30), Charges INT);

# Insert values into the database
## Customer data
INSERT INTO customer_master VALUES('cust1', 'vijay', 4, '2023/03/12'), ('cust2', 'sushila', 13, '2023/03/21'), ('cust3', 'fernandas', 11, '2022/11/04');
INSERT INTO customer_master VALUES('cust4', 'shubham', 19, '2023/02/15'), ('cust5', 'shivani', 27, '2023/02/01'), ('cust6', 'pooja', 11, '2022/05/24');

## Transaction data
INSERT INTO transactions VALUES('transact1', 'cust3', 2, 1200), ('transact2','cust2', 5, 3450), ('transact3', 'cust4', 1, 500), ('transact4', 'cust3', 1, 304), ('transact5', 'cust1', 1, 13000), ('transact6', 'cust6', 2, 2934), ('transact7', 'cust5', 9, 9023);

## Shipping data
INSERT INTO delivery_charges VALUES('mum', 'Mumbai', 20), ('del', 'Delhi', 15), ('hyd', 'Hyderabad', 20), ('pun', 'Pune', 20), ('sur', 'Surat', 25), ('ahm', 'Ahmedabad', 20), ('ban', 'Bangalore', 10), ('man', 'Mangalore', 30), ('luc', 'Lucknow', 25), ('bho', 'Bhopal', 25), ('cha', 'Chandigarh', 25), ('kol', 'Kolkata', 25);

# Update table
## Customer data location
ALTER TABLE customer_master ADD Location_ID VARCHAR(10);

UPDATE customer_master SET Location_ID = CASE customer_name WHEN 'vijay' THEN 'ban' WHEN 'sushila' THEN 'sur' WHEN 'fernandas' THEN 'mum' WHEN 'shubham' THEN 'pun' WHEN 'shivani' THEN 'man' WHEN 'pooja' THEN 'luc' ELSE 'na' END;

## Customer demographics (Age, Sex)
ALTER TABLE customer_master ADD sex VARCHAR(10), ADD age INTEGER;

UPDATE customer_master SET sex = CASE customer_name WHEN 'vijay' THEN 'male' WHEN 'sushila' THEN 'female' WHEN 'fernandas' THEN 'male' WHEN 'shubham' THEN 'male'
WHEN 'shivani' THEN 'female' WHEN 'pooja' THEN 'female' ELSE 'na' END, age = CASE customer_name WHEN 'vijay' THEN 25 WHEN 'sushila' THEN 22 WHEN 'fernandas' THEN 37 WHEN 'shubham' THEN 32 WHEN 'shivani' THEN 31 WHEN 'pooja' THEN 20 END;

# Analysis
## Calculate Total Revenue generated by each customer
SELECT a.Customer_name, SUM(b.Amount) FROM customer_master a INNER JOIN Transactions b on a.ID=b.Customer_ID GROUP BY a.Customer_name;

## Calculate Token size for each customer
SELECT a.customer_name, ROUND(SUM(b.Amount)/SUM(b.Quantity), 2) as token_size FROM customer_master a INNER JOIN transactions b on a.ID=b.Customer_ID GROUP BY a.customer_name;

## Calculate quantity of items bought by each customer
SELECT a.customer_name, SUM(b.Quantity) as total_quantity FROM customer_master a INNER JOIN transactions b on a.ID=b.Customer_ID GROUP BY a.customer_name;

## Calculate Logistics cost for each customer
SELECT a.customer_name, (a.transactions*b.Charges) AS Logistics_cost FROM customer_master a JOIN delivery_charges b ON a.Location_ID=b.Location_ID;

## Calulate Logistics cost for each location
SELECT b.Location, (a.transactions*b.Charges) AS Logistics_cost FROM customer_master a JOIN delivery_charges b ON a.Location_ID=b.Location_ID;

## Calculate Revenue and transactions by gender type
SELECT a.sex, SUM(a.transactions) as Transactions, SUM(b.Amount) as Revenue FROM customer_master a JOIN transactions b ON a.ID=b.Customer_ID GROUP BY a.sex;


